# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [30]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint 

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [31]:
# Study data files
part_one = "C:/Users/test/Desktop/python-api-challenge/weatherpy/Resources/citiesall.csv"
part_one = pd.read_csv(part_one)
part_one

,City,Country,Temperature(F),Latitude,Longitude,Humidity(%),Cloudiness(%),Windspeed(mph)
0,doha,QA,53.20,25.29,51.53,66.0,0.0,3.36
1,sur,OM,62.64,22.57,59.53,59.0,0.0,9.91
2,nikolskoye,RU,23.95,59.70,30.79,85.0,90.0,6.71
3,nabire,ID,88.93,-3.37,135.48,59.0,100.0,5.35
4,hobart,AU,71.47,-42.88,147.33,36.0,20.0,17.22
...,...,...,...,...,...,...,...,...
594,severobaykalsk,NO,21.79,70.37,31.11,66.0,100.0,8.23
595,pangai,PH,83.05,6.21,124.19,72.0,8.0,2.64
596,buraydah,GB,33.30,55.76,-4.86,97.0,100.0,2.24
597,shahrud,NaN,68.13,-17.47,16.33,86.0,65.0,4.99
598,sakaiminato,MM,62.94,22.93,97.75,42.0,0.0,1.43

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [32]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

In [45]:
# Store 'Lat' and 'Lng' into  locations 
locations = part_one[["Latitude", "Longitude"]]

In [46]:
part_one = part_one.dropna()

In [47]:
humi = part_one["Humidity(%)"]

In [48]:
fig = gmaps.figure(center=(20.0,0.0),zoom_level=2)

heat_layer = gmaps.heatmap_layer(locations, weights=humi, dissipating = False, max_intensity=100, point_radius = 5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [7]:
#ideal vacation conditions:1. max temperature 75<x<90 2. Cloudiness <20% 3. Humidity <40%

In [36]:
ideal_df=part_one[(part_one['Temperature(F)']>75) & (part_one['Temperature(F)']<90) & (part_one['Humidity(%)']<40) & (part_one['Cloudiness(%)']<20)]
ideal_df

,City,Country,Temperature(F),Latitude,Longitude,Humidity(%),Cloudiness(%),Windspeed(mph)
40,ponta do sol,AU,87.22,-33.65,115.33,23.0,0.0,10.83
355,esperanza,AR,78.98,-33.30,-66.34,36.0,0.0,16.06
407,saleaula,AR,77.14,-42.77,-65.04,17.0,10.0,15.21
448,puerto madryn,AU,88.72,-33.37,116.15,23.0,0.0,6.22

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [37]:
hoteln_df=[]
hotel_df=ideal_df
hotel_df['Hotel Name']= ""
hotel_df

C:\Users\test\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,City,Country,Temperature(F),Latitude,Longitude,Humidity(%),Cloudiness(%),Windspeed(mph),Hotel Name
40,ponta do sol,AU,87.22,-33.65,115.33,23.0,0.0,10.83,
355,esperanza,AR,78.98,-33.30,-66.34,36.0,0.0,16.06,
407,saleaula,AR,77.14,-42.77,-65.04,17.0,10.0,15.21,
448,puerto madryn,AU,88.72,-33.37,116.15,23.0,0.0,6.22,

In [38]:
target_type = "lodging"
radius = 5000

params = {
    "types": target_type,
    "radius": radius,
    "key": g_key
}
   # Use the lat/lng we recovered to identify airports
for index, row in hotel_df.iterrows():
    
    # get lat, lng from df
    lat = row["Latitude"]
    lng = row["Longitude"]
    
    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response = requests.get(base_url, params=params)
    response_json=response.json()
    #pprint(response_json)
    hoteln_df.append(response_json['results'][0]['name'])
    
    hotel_df.loc[index, "Hotel Name"] = response_json["results"][0]["name"]
    
    print(f"The closest hotel to {row[0]} is {response_json['results'][0]['name']}")

The closest hotel to ponta do sol is Observatory Guest House
The closest hotel to esperanza is Huarpes Hotel
The closest hotel to saleaula is Hotel Tolosa
The closest hotel to puerto madryn is Collie Ridge

In [39]:
hotel_df

,City,Country,Temperature(F),Latitude,Longitude,Humidity(%),Cloudiness(%),Windspeed(mph),Hotel Name
40,ponta do sol,AU,87.22,-33.65,115.33,23.0,0.0,10.83,Observatory Guest House
355,esperanza,AR,78.98,-33.30,-66.34,36.0,0.0,16.06,Huarpes Hotel
407,saleaula,AR,77.14,-42.77,-65.04,17.0,10.0,15.21,Hotel Tolosa
448,puerto madryn,AU,88.72,-33.37,116.15,23.0,0.0,6.22,Collie Ridge

In [49]:
hotel_df.dropna(how="any")

,City,Country,Temperature(F),Latitude,Longitude,Humidity(%),Cloudiness(%),Windspeed(mph),Hotel Name
40,ponta do sol,AU,87.22,-33.65,115.33,23.0,0.0,10.83,Observatory Guest House
355,esperanza,AR,78.98,-33.30,-66.34,36.0,0.0,16.06,Huarpes Hotel
407,saleaula,AR,77.14,-42.77,-65.04,17.0,10.0,15.21,Hotel Tolosa
448,puerto madryn,AU,88.72,-33.37,116.15,23.0,0.0,6.22,Collie Ridge

In [41]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in ideal_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [44]:
# Add marker layer ontop of heat map

# Configure gmaps with API key
gmaps.configure(api_key=g_key)

# Display Map

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=hotel_info,
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)
fig

TraitError:
<dl>
<dt>Name</dt><dd>Observatory Guest House</dd>
<dt>City</dt><dd>ponta do sol</dd>
<dt>Country</dt><dd>AU</dd>
</dl>
 is not a valid weight. Weights must be floats